# Generated by Django 2.0.2 on 2018-06-14 09:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_one', models.CharField(max_length=100)),
                ('incorrect_two', models.CharField(max_length=100)),
                ('incorrect_three', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=6)),
                ('category', models.CharField(default='General Knowledge', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('players', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tournement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Tournement'),
        ),
    ]
